baseURL: "https://akshay-chauhan-000.github.io/"
title: Akshay Chauhan
theme: PaperMod

pagination:
  pagerSize: 40

taxonomies:
  tag: tags

menu:
  main:
    - name: About
      url: /about/
      weight: 1

    - name: Teaching
      url: /teaching/
      weight: 2

    - name: Projects & Publications
      url: /projects/
      weight: 3

    - name: Tutorials
      url: /tutorials/
      weight: 4

    - name: ML / AI
      url: /ml-ai/
      weight: 5

    - name: Blog
      url: /blog/
      weight: 6

    - name: Fitness
      url: /fitness/
      weight: 7

params:
  description: "Academic website of Akshay Chauhan. Research in computational polymer physics, soft matter, and biophysics using large-scale simulations and theory."
  author: Akshay Chauhan
  googleAnalyticsID: ""   # add later if needed
  images: ["cover.png"]
  DateFormat: "January 2006"

  defaultTheme: light
  hideFooter: true
  disableThemeToggle: true

  ShowShareButtons: false
  ShowReadingTime: false
  ShowWordCount: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  disableScrollToTop: true
  ShowCodeCopyButtons: true
  ShowToc: false
  TocOpen: false
  UseHugoToc: true
  comments: false
  math: true

  profileMode:
    enabled: true
    title: Akshay Chauhan
    subtitle: >
      PhD candidate in Computational Polymer Physics.
      I study conformations of charged-uncharged polymers under solutions with different ionic strengths, macromolecular crowding; self-assembly of polyelectrolyte
      using coarse-grained simulations, statistical physics, and data-driven modeling.
    imageUrl: "/picture.jpeg"
    imageWidth: 130
    imageHeight: 130
    buttons:
      - name: About
        url: /about/
      - name: Teaching
        url: /teaching/
      - name: Projects
        url: /projects/
      - name: Tutorials
        url: /tutorials/
      - name: ML / AI
        url: /ml-ai/
      - name: Blog
        url: /blog/
      - name: Fitness
        url: /fitness/

  socialIcons:
    - name: CV
      url: /cv.pdf
    - name: Email
      url: mailto:akshay.chauhan@students.iiserpune.ac.in
    - name: Google Scholar
      url: https://scholar.google.com/citations?user=Wmk0GMoAAAAJ&hl=en
    - name: ORCID
      url: https://orcid.org/0009-0005-7101-6274
    - name: GitHub
      url: https://github.com/akshay-chauhan-000
    - name: instagram
      url: https://www.instagram.com/grumpy_molecule/

  assets:
    disableScrollBarStyle: true

  cover:
    hiddenInList: true
    hiddenInSingle: true

  label:
    text: "Akshay Chauhan"

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    guessSyntax: true
    style: xcode

  tableOfContents:
    startLevel: 2
    endLevel: 2
    ordered: false

enableInlineShortcodes: true
enableRobotsTXT: true
titleCaseStyle: "none"
enableGitInfo: true
buildFuture: true
